[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build && mkdir -p dist/functions && cp functions/socket-io.js dist/functions/"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/socket-io/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run start"
  port = 5173
  targetPort = 5173
  autoLaunch = true
